find_package(apr REQUIRED)
find_package(openssl REQUIRED)
if(UNIX)
  include(configure.cmake)
endif()
include(CheckCXXCompilerFlag)
check_cxx_compiler_flag("-Wno-deprecated-declarations" has_noDeprecatedDeclarations)
if(has_noDeprecatedDeclarations)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated-declarations")
endif()
add_subdirectory(src/main)
add_subdirectory(src/examples)
